def mostrar_menu():
    return """
         "┌───── JASER MENÚ ─────┐\n"
         "│ ✨ ¡Bienvenido a Japer! ✨ │\n"
         "│ ⚙️ ¿Cómo te puedo ayudar? ⚙️ │\n"
         "├─────────────────────────┤\n"
         "|     ECONOMÍA     |     │\n"
         "| `.trabajar o .work o .w` - Gana dinero\n"
         "| `.crimen` - Gana dinero\n"
         "| `.diario` - Gana dinero\n"
         "| `.cofre` - Gana dinero\n"
         "| `.apostar` - Gana dinero\n"
         "| `.depositar` - Deposita dinero\n"
         "| `.retirar` - Retira dinero\n"
         "| `.banco` - Consulta el estado de tu cuenta\n"
         "├─────────────────────────┤\n"
         "|     INTERACCIÓN     |     │\n"
         "| (PROXIMAMENTE)     |     │\n"
         "└─────────────────────────┘\n"
     """